accounts:
  - name: alice
    coins: ["2000000000uatom", "1000000000uiris", "1000000000udvpn", "1000000000uxprt", "1000000000ucro", "1000000000uakt", "200000000stake"]
  - name: bob
    coins: ["2000uatom", "1000uiris", "1000udvpn", "1000uxprt", "1000ucro", "1000uakt", "200000000stake"]
validator:
  name: alice
  staked: "100000000stake"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
